import { deleteReport, getReport, readReportDoc } from "@/lib/store";
import { fmtCost, fmtDuration } from "@/lib/format";
import { SOURCE_MARKER, sourceBannerHtml } from "@/lib/sources";
import type { ReportMeta } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function metaFooter(meta: ReportMeta | undefined): string {
  if (!meta) return "";
  const parts = [
    fmtDuration(meta.durationMs),
    fmtCost(meta.costUsd) ? `${fmtCost(meta.costUsd)} API cost` : "",
  ].filter(Boolean);
  if (parts.length === 0) return "";
  return `<div style="font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:#9aa3b2;background:#0b0d13;border-top:1px solid #2a2f40;padding:10px 16px;text-align:center">Generated by Repo Explorer · ${parts.join(" · ")}</div>`;
}

// /api/reports/<id>            -> the report's index.html
// /api/reports/<id>/<doc>      -> a follow-up document in the report folder
export async function GET(
  _req: Request,
  ctx: { params: Promise<{ path: string[] }> },
) {
  const { path } = await ctx.params;
  const [id, doc] = path;
  const html = await readReportDoc(id, doc ?? "index");

  if (!html) {
    const meta = await getReport(id);
    const message =
      meta?.status === "running"
        ? "This report is still being generated."
        : meta?.status === "error"
          ? `This analysis failed: ${meta.error ?? "unknown error"}`
          : "Report not found.";
    return new Response(
      `<!doctype html><meta charset="utf-8"><body style="font:16px system-ui;background:#0f1115;color:#9aa3b2;padding:40px">${message}</body>`,
      { status: meta ? 200 : 404, headers: { "Content-Type": "text/html; charset=utf-8" } },
    );
  }

  // The report renders inside a sandboxed iframe. Inject a <base target="_blank">
  // so citation links open in a new tab instead of navigating the sandboxed frame.
  const meta = await getReport(id);
  const footer = metaFooter(meta);
  let out = html
    .replace(/<head([^>]*)>/i, `<head$1><base target="_blank">`)
    .replace(/<\/body>/i, `${footer}</body>`);

  // Fallback for docs generated without the source banner baked in.
  if (!out.includes(SOURCE_MARKER)) {
    out = out.replace(
      /<body([^>]*)>/i,
      `<body$1>${sourceBannerHtml(meta?.repos ?? [])}`,
    );
  }

  return new Response(out, {
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}

// /api/reports/<id> -> delete the whole report (folder + index entry).
export async function DELETE(
  _req: Request,
  ctx: { params: Promise<{ path: string[] }> },
) {
  const { path } = await ctx.params;
  const [id] = path;
  if (!id) return new Response("Bad request", { status: 400 });
  await deleteReport(id);
  return new Response(null, { status: 204 });
}
